ARG BASE_IMAGE=ubuntu:latest
FROM $BASE_IMAGE
ENV DEBIAN_FRONTEND=noninteractive 
RUN : \
 && apt-get update \
 && apt-get install -y git golang-go \
 && rm -rf /var/lib/apt/lists/* \
;
RUN go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
RUN mv /root/go/bin/docker-credential-ecr-login /
