version: '3.7'

# Note: environment variables are set in .env

services:

  gitlab-server:
    image: 'gitlab/gitlab-ce:latest'
    # restart: always
    hostname: 'gitlab-server'
    container_name: gitlab-server
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-server:${GITLAB_SERVER_WEB_PORT}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SERVER_SSH_PORT}
    ports:
      - '127.0.0.1:${GITLAB_SERVER_WEB_PORT}:${GITLAB_SERVER_WEB_PORT}'
      - '127.0.0.1:${GITLAB_SERVER_SSH_PORT}:${GITLAB_SERVER_SSH_PORT}'
    volumes:
      - './gitlab-server-mounts/config:/etc/gitlab'
      - './gitlab-server-mounts/logs:/var/log/gitlab'
      - './gitlab-server-mounts/data:/var/opt/gitlab'
    networks:
      - gitlab-network


  gitlab-runner1:
    image: gitlab/gitlab-runner:$GITLAB_RUNNER_TAG
    # restart: always

    # Although the runner is not itself privileged, we still forward the
    # Docker socket, and the runner config allows it to create privileged
    # containers.
    privileged: false

    volumes:
      - './gitlab-runner1-config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
      #
      # The bind mounts below apply to the runner's Docker executor, but
      # not DinD. (The corresponding mounts for DinD are set up in the
      # runner's "config.toml" via the "register" script.)
      #
      # Note: the Docker executor also requires "DOCKER_AUTH_CONFIG" to
      # be set in "config.toml".
      - '$RUNNER_CREDENTIALS_FILE:/root/.aws/credentials:ro'
      - './build-amazon-ecr-credential-helpers/docker-credential-ecr-login-gitlab-runner_$GITLAB_RUNNER_TAG:/usr/local/bin/docker-credential-ecr-login:ro'

    networks:
      - gitlab-network


networks:
  gitlab-network:
    name: gitlab-network
