version: '3.7'

services:

  gitlab-runner1:
    image: gitlab/gitlab-runner:$GITLAB_RUNNER_TAG
    restart: always
    container_name: gitlab-runner1
    hostname: gitlab-runner1
    privileged: false
    volumes:
      - './runner1-config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
#      - './dind-config.template.toml:/root/dind-config.template.toml'
      # These credentials plus helper are used by the runner itself to use non-public images.
      # They do not apply to dind, i.e. the ability to use non-public images from a
      # gitlab-ci.yml script. The latter is configured in the runner's config.toml.
      - '$HOME/.aws/credentials:/root/.aws/credentials:ro'
      - './build-amazon-ecr-credential-helpers/docker-credential-ecr-login-gitlab-runner_$GITLAB_RUNNER_TAG:/usr/local/bin/docker-credential-ecr-login:ro'
