version: '3.7'

# Note: environment variables are set in .env

services:

  gitlab-runner1:
    image: gitlab/gitlab-runner:$GITLAB_RUNNER_TAG
    # restart: always
    container_name: gitlab-runner1
    hostname: gitlab-runner1

    # Although the runner is not itself privileged, we still forward the
    # Docker socket, and the runner config allows it to create privileged
    # containers.
    privileged: false

    volumes:
      - './gitlab-runner1-config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
      #
      # The credentials and helper are used by the runner itself to access
      # private images via a .gitlab-ci.yml line of the form
      #
      #   image: 123456789012.dkr.ecr.eu-central-1.amazonaws.com/repo:tag
      #
      # They do NOT apply to dind, i.e. the ability to use non-public 
      # images from within a gitlab-ci.yml script, namely
      #
      #   image: docker:19.03.12
      #   script:
      #     - docker pull 123456789012.dkr.ecr.eu-central-1.amazonaws.com/repo:tag
      #
      # The latter is configured in the runner's config.toml via the
      # register script.
      - '$RUNNER_CREDENTIALS_FILE:/root/.aws/credentials:ro'
      - './build-amazon-ecr-credential-helpers/docker-credential-ecr-login-gitlab-runner_$GITLAB_RUNNER_TAG:/usr/local/bin/docker-credential-ecr-login:ro'
