#!/bin/bash


# https://stackoverflow.com/a/246128/10155767 (Dave Dopson)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


# Make sure we are in the correct directory.
if [ "$DIR" != "$PWD" ]; then
  echo "Please run this script from $DIR"
  exit 1
fi

# Read environment variables
source .env

docker-compose exec gitlab-runner1 gitlab-runner register \
  --executor docker \
  \
  `# No default image, always specify in .gitlab-ci.yml.` \
  --docker-image scratch \
  \
  `# Required for DinD.` \
  --docker-privileged \
  \
  `# IMPORTANT: The source paths of all bind-mount volumes are on the` \
  `#            runner's host, and NOT in the gitlab-runner container.` \
  \
  --docker-volumes "$PWD/gitlab-runner1-mounts/client-certs:/certs/client" \
  --docker-volumes "$PWD/gitlab-runner1-mounts/cache:/cache" \
  \
  `# Required for DinD (not the runner's Docker executor) to find the credentials helper.` \
  --docker-volumes "$PWD/config-docker.json:/root/.docker/config.json" \
  \
  `# Credentials for DinD.` \
  --docker-volumes "$RUNNER_CREDENTIALS_FILE:/root/.aws/credentials:ro" \
  \
  `# Credentials helper for DinD.` \
  --docker-volumes "$PWD/build-amazon-ecr-credential-helpers/docker-credential-ecr-login-docker_$DOCKER_IMAGE_TAG:/usr/local/bin/docker-credential-ecr-login:ro" \
  \
  `# Required for the runner's Docker executor (not DinD) to find the credentials helper.` \
  --env 'DOCKER_AUTH_CONFIG={ "credsStore": "ecr-login" }' \
;
